apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-persitent-volume-claim
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi