apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-nfs-persitent-volume
  namespace: home-assistant                                
spec:
  capacity:
    storage: 10Gi
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /export/nasty/appdata/Home-Assistant-Core/                             
    server: 10.10.20.10
  claimRef:
    namespace: home-assistant
    name: home-assistant-persitent-volume-claim                      
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-persitent-volume-claim
  namespace: home-assistant                    
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi       